Kludex/awesome-pydantic

- awesome.yaml
This PR adds autodoc_pydantic.
> Add autodoc_pydantic

- awesome.yaml
> Add Quart-Schema

- awesome.yaml
@Kludex I'm from https://github.com/mjhea0/awesome-fastapi/pull/91 :smiley:
> 📝 Add pydantic-i18n

- awesome.yaml
Hi,
I'm the developer of pydantic-aioredis. I thought it might be useful to more people, so I added it to your list!
> add pydantic-aioredis

- awesome.yaml
We use Pydantic heavily in our open source Kubernetes automation platform.
> Add robusta.dev

- awesome.yaml
Add Redis-OM-Python, Please review it :)
> Add redis-om-python

- awesome.yaml
Hi @Kludex, here's yet another way to use Pydantic in Django
> Add django-pydantic-field

- .github/actions/awesome/main.py
- .github/actions/awesome/requirements.txt
- README.md.jinja
- awesome.yaml
Add a category for the `awesome` list, but I'm not sure the classification is suitable.
Category list:
- Machine Learning
- Object Mapping
- Utilities
- Web
Maybe it can more specific.
> Automate category awesome list

- awesome.yaml
This change doesn't need review, I'll merge it directly. cc @Kludex
> Fix some repositories incorrect category

- awesome.yaml
https://github.com/andrewthetechie/pydantic-sqs
> add pydantic-sqs to awsome.yaml

- awesome.yaml
https://github.com/adamsussman/pydantic-enhanced-serializer/
> Add pydantic-enhanced-serializer

- awesome.yaml
> Add DocArray

- awesome.yaml
Added a new python package `Laktory` to the awesome.yaml configuration file. This is a new package helping data specialists to build data platforms. More information available here: www.laktory.ai
> Added Laktory

- awesome.yaml
a light-weight package for generating `GraphQL-like response` data.
> add pydantic-resolve

- awesome.yaml
Adding settings-doc into the list. Suggested in https://github.com/pydantic/pydantic/issues/8962#issuecomment-1983303848
> Add `settings-doc` to the Utilities list

- awesome.yaml
Simple PR to mention [`pydantic-numpy`](https://github.com/caniko/pydantic-numpy)
**Reviewer**
@sydney-runkle
> Add pydantic-numpy

- awesome.yaml
> Add Mirascope

- awesome.yaml
Reverts Kludex/awesome-pydantic#62
> Revert "Add `fodantic`"

- awesome.yaml
Reverts Kludex/awesome-pydantic#65
> Revert "Revert "Add `fodantic`""

- awesome.yaml
ContextGem is a free, open-source LLM framework that makes it radically easier to extract structured data and insights from documents - with minimal code. It's built on Pydantic for data validation and modeling.
> Add ContextGem
